name: timer
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  wave: ^0.2.0

dev_dependencies:
  bloc_test: ^8.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
